### ISSUE TITLE
Audio problems

### ISSUE THREAD

**Issue by paxinos** [conexant/alexa-avs-sample-app#1]
I've rebuilt the kernel a few times to make sure I was not missing any steps. I can play music through the speaker without problems (connected to the line out of the Conexant Board). However recording is not working. Both the 'recordingAgent' and 'arecord' fail with the same error "No such file or directory".

I have also verified that the file .asoundrc was properly copied.

Below is the output of a few linux commands. Please note the 'international' characters that are port of the Capture device name - those are in the output and copied here correctly.

pi@raspberrypi-alexa:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: cxsmtspkpiusb [cxsmtspk-pi-usb], device 0: System Playback cx2072x-dsp-0 []
Subdevices: 1/1
Subdevice #0: subdevice #0
pi@raspberrypi-alexa:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CX20924çï [CX20924çï·], device 0: USB Audio [USB Audio]
Subdevices: 1/1
Subdevice #0: subdevice #0
pi@raspberrypi-alexa:~ $ arecord /tmp/test.wav
arecord: main:722: audio open error: No such file or directory
pi@raspberrypi-alexa:~ $

**Comment by mcornejo** [comment]
@paxinos Does your .asoundrc look like this?

```pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "hw:0,0"
    }
    capture.pcm {
        type plug
        slave.pcm "hw:1,0"
    }
}

**Comment by paxinos** [comment]
Thanks, unfortunately what I had was the original file in leftarc.     When
I changed it worked - sort of - more below.

Interestingly, when I power cycle the device, sometimes I need to use
hw:1,0, sometimes I need to use the original leftarc file.   I haven't
found a pattern.

Also, as to the 'sort of', I can get the software started.    Query Alexa,
and then it speaks the response for about 1 to 2 seconds and then stops.
The only way to get it to work again is to kill/start the Java client and
the audio recorder.     I've tired with and without the wake word
recognition.    I've also try power cycling the device.


http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by Thorarinns** [comment]
Hi @paxinos,
If you use (plug)hw:1,0 then you shouldn't be able to use both the Recording Agent and the Wake Word Agent at the same time, since only one application can record directly from a device at a time.
Or it shouldn't work correctly that is.  The leftarc .asoundrc file uses the dsnoop ALSA plugin to fix that.

The .asoundrc file is changed every time you restart and the default device is changed to hw 0, which you can't record from.
If you try to do that you get the "No such file or directory" error.

The startup.sh script copies the leftarc file over the .asoundrc file to address this.
Are you running it or are you manually starting each program?

You seem to have correctly built the kernel since you are able to play audio.

I wasn't able to duplicate the problem so I probably need more information.
Can you copy the leftarc over the .asoundrc and run:
arecord /tmp/test.wav -D left -r 16000 -f s16_le

**Comment by paxinos** [comment]
When running the command as given it works both with hw 1 and with the
original file.    It aps the .asoundrc is rewritten at some point with the
these lines add:

49,59d48
<
<
< pcm.!default {
<       type hw
<       card 0
< }
<
< ctl.!default {
<       type hw
<       card 0
< }


When those lines are added arecord no longer works and gets the file not
found error.

Also, there is an error in startup.sh    it tries to 'cp ~/leftarc
~/.asoundrc'     But the file is not in ~/ but in a subdirectory...
 The instructions state to cp leftarc to ~/.asoundrc     So I've created a
symlink so the startup script works - but that needs to be addressed in
either the sample script or instructions.

At this point I can get Alexa working (so far without the wake word
process).  But only for a couple interactions.   It seems to stop speaking
mid sentence and then hangs.  I need to restart all processes to get it to
work - including the LED process(?)

Ok, on further testing it seems the LED process is hanging up.   If I don't
start it then the Alexa code works fine - including the wake word engine.
 So what should I looking regarding the LED hw and process?

*Thanks,*
Pax.



http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by Thorarinns** [comment]
Hey Pax,

Are you using a Raspberry Pi 3?
The LED signal and audio signal don't mix on RPi 3, so we tell people to use the RPi 2.

Regards,
Thor

**Comment by paxinos** [comment]
Ahh, that must be it.

Any chance RPi 3 will be supported soon?     We will likely need the extra
performance for our product.

Thanks,
Pax.

http://www.siggraph.org/~pax/
http://www.linkedin.com/in/garrypaxinos

*ΓΝΩΘΙ ΣΑΥΤΟΝ*

"The real voyage of discovery consists not in seeking new landscapes but in
having new eyes." -Proust

"Wherever you go, go with all of your heart" -Confucius

**Comment by shuai320** [comment]
Sorry, we don’t have plans to support RPi3 in the near term because of an issue found with RPi3.
