### ISSUE TITLE
problems with the speaker

### ISSUE THREAD

**Issue by soarsf** [conexant/alexa-avs-sample-app#2]
Hi, ​I'm new to linux and tried to follow this guide, and encountered several issues .

1, I used win7 and mstsc to login to pi instead of using a HDMI monitor, would that work?

2, do I have to connect the speaker to the conexant board before Step 7: Run the automated install script? I wonder if a driver was installed because, 

3, in Step 9 I tried to use an iphone earphone and a usb-powered speaker, the results were the same: if the earphone/speaker was connected before the boards were powered up, the sample app showed "There was a problem connecting to the Companion Service. Trying again in 2 seconds. Please make sure it is up and running. " and no authenticate window would pop up. If the earphone/speaker was connected after the tokens were ready, I could speak to Alexa, and then the app showed "ERROR com.amazon.alexa.avs.AVSAudioPlayer - An error occurred while trying to play audio javazoom.jl.decoder.JavaLayerException: Cannot create AudioDevice". What caused the problem?

**Comment by Thorarinns** [comment]
Hi @soarsf ,

1. I'm a little confused, are you asking if it's possible to do, or did you manage to do it and are asking if it would cause problems?

2. No it should not matter at all.

3. I will need some more information from you, 
You can start by sending me what gets written out when you type both
aplay -l
arecord -l

**Comment by soarsf** [comment]
Thanks for the reply.
1. I did do it, and I was afraid that was the cause of the problem
2. glad to hear
3. the default audio device was disabled, and the speaker was connected to the conexant board. The output is as below:
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CX20924▒▒ [CX20924ਲ਼ࠜ], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

PS, I tested the speaker and the pi without the conexant board, when default audio device was enabled, the speaker worked fine.

**Comment by Thorarinns** [comment]
Step 8: Building/Installing the Linux Kernel is necessary to get the system working correctly,
If you made a mistake in it then the device will not show up in the list of playback devices.

Regards,
Thor

**Comment by soarsf** [comment]
Thanks, I'll try again

**Comment by Thorarinns** [comment]
Hey @soarsf, 
Someone committed experimental code to https://github.com/conexant/rpi-linux that didn't work properly with our board (but it should have still shown up).
I've reverted it but you should start again from the "Get sources" step found there.

Regards,
Thor

**Comment by soarsf** [comment]
After rebuilding, everything worked perfectly fine, thanks for your guidance

**Comment by soarsf** [comment]
Btw, can I recorded my voice & get output files with this app?

**Comment by Thorarinns** [comment]
You can go on alexa.amazon.com to Settings->History and listen to/download what gets sent to Alexa.

You can record directly from the device with the arecord command, type "arecord -h" to see list of options.
