### ISSUE TITLE
Can't start LED server

### ISSUE THREAD

**Issue by SonicScape** [conexant/alexa-avs-sample-app#3]
I followed the instructions to bring up the system, when I try to run the LED server with the following command,
`cd ~/alexa-avs-sample-app/samples/tLED && sudo python tLEDServer.py`

I got the error message below,
```
Traceback (most recent call last):
  File "tLEDServer.py", line 33, in <module>
    cControl = tLED.cc.colorControl()
  File "/home/pi/alexa-avs-sample-app/samples/tLED/colorControl.py", line 36, in __init__
    self.strip.begin()
  File "build/bdist.linux-armv7l/egg/neopixel.py", line 102, in begin
RuntimeError: ws2811_init failed with code -1

```

I can talk to the kit and get a response from Alexa. The javaclient, wakeupwordagent, recording agent all seem to work. But the LED ring would not light up.
Please advise, thanks.

**Comment by Thorarinns** [comment]
Hi @SonicScape, we found out what the problem was and we will fix it hopefully later today.

Regards,
Thor

**Comment by SonicScape** [comment]
Hi, Thor, Thanks for the update, look forward to the fix. 
BR

**Comment by Thorarinns** [comment]
Hi @SonicScape,  this should do the trick.
Just do a git pull from the sample-app directory and run the installer again.

Regards,
Thor

**Comment by SonicScape** [comment]
It's working now, thanks!
