### ISSUE TITLE
How to get sound direction information on CX20924 EVK?

### ISSUE THREAD

**Issue by MikeYen** [conexant/alexa-avs-sample-app#8]
Hi
Is there any document describe how CX20924 EVK get Wake Word sound direction?
and where in code that I can receive sound direction signal? 

Thanks~

**Comment by Thorarinns** [comment]
Hi @MikeYen,
In https://github.com/conexant/alexa-avs-sample-app/blob/master/samples/tLED/tLED.py
In the method DOA in line 85.

You'd have to do something similar
